components:
    schemas:
        Specialty:
            properties:
                id:
                    format: int32
                    type: integer
                name:
                    type: string
                new:
                    type: boolean
            type: object
        Vet:
            properties:
                firstName:
                    type: string
                id:
                    format: int32
                    type: integer
                lastName:
                    type: string
                new:
                    type: boolean
                nrOfSpecialties:
                    format: int32
                    type: integer
                specialties:
                    items:
                        $ref: '#/components/schemas/Specialty'
                    type: array
                specialtiesInternal:
                    items:
                        $ref: '#/components/schemas/Specialty'
                    type: array
                    uniqueItems: true
                    writeOnly: true
            required:
                - firstName
                - lastName
            type: object
        Vets:
            properties:
                vetList:
                    items:
                        $ref: '#/components/schemas/Vet'
                    type: array
            type: object
info:
    title: OpenAPI definition
    version: v0
openapi: 3.0.1
paths:
    /vets:
        get:
            operationId: showResourcesVetList
            responses:
                "200":
                    content:
                        '*/*':
                            schema:
                                $ref: '#/components/schemas/Vets'
                    description: OK
            tags:
                - vet-controller
servers:
    - url: http://petclinic-knative.my-apps.maz-tap-2610.tapdemo.vmware.com
