apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: root
  description: The infra business unit
spec:
  type: team
  profile:
    displayName: Root
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  children: [config, rutime]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: config
  description: The infra business unit
spec:
  type: team
  profile:
    displayName: Config
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  parent: root
  children: [dili]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: acme-spi-space
  description: The infra business unit
spec:
  type: team
  profile:
    displayName: acme-spi-space
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  parent: root
  children: [devspace]
---
