apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: root
  description: The infra business unit
spec:
  type: team
  profile:
    displayName: Root
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  children: [project]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: project
  description: The infra business unit
spec:
  type: team
  profile:
    displayName: project
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  parent: root
  children: [config]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: config
  description: The infra business unit
spec:
  type: team
  profile:
    displayName: config
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  parent: project
  children: [acme-api-space]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: acme-api-space
  description: The infra business unit
spec:
  type: team
  profile:
    displayName: acme-api-space
    email: infrastructure@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg
  parent: project
  children: [acme-dev-space]
